## Multiple linear regression with SKlearn

In [5]:
#import the neccessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
sns.set()
#and of course the actual regression(manchine learning)module
from sklearn.linear_model import LinearRegression

Load the data

In [6]:
data=pd.read_csv(r'C:\Users\dell\Documents\Multiple Linear Regression\1.02.+Multiple+linear+regression (2).csv')
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

Describe the data

In [7]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

Declare the dependent and independent

In [8]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

Regresion itself

In [9]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [10]:
#Gettin the coefficients of the regression
reg.coef_
#note tat the output is an array

array([ 0.00165354, -0.00826982])

In [11]:
#Gettiong the intercept of the regression
reg.intercept_
#Note that the result is a float as we usually expect a single value

0.29603261264909486

##calculating the R-squared

In [12]:
#Get thre R-squared of the regression
reg.score(x,y)

0.40668119528142843

# Formular for Adjusted R^2
$R^2_{adj.}=1-(l-R^2)*\frac{n-1}{n-p-1}$

In [13]:
#Get the shape of x,to facilitate the creation of the Adjusted R^2 metric
x.shape

(84, 2)

In [14]:
#if we want to find the Adjusted R-squared,we can do so by knowing the r2, the observation,the feautures
r2=reg.score(x,y)
# Number of observation is the shape along axis 0
n=x.shape[0]
# Number of features (predictors,p)is the shape along axis 1
p=x.shape[1]

#We find the Adjusted R-squared using the formular
adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

Feature selection

In [4]:
#import the feature selection module from sklearn
#This module helps to select the most appropriate features for our regression
#There exists many different approaches to feature selection,howeveer.we will use one of the simplest
from sklearn.feature_selection import f_regression

In [16]:
#We will look into:f_regression
#f_regression find the F-statistics for the*simple* regression created with each of the independent variables
#in our case, this would mean running a simple linear regression on GPA where SAT is the independen variable
#and a siple linear regression on GPA where Rand 123 s the independent variable
#The limitation of this approach is that it does not take into account the mutual effect of the two features
f_regression(x,y)

#There are tw0 output arrays
#The firstone contains the f-statistics for each of the regressions
#The second one contains the p-values of these f-statistics


(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [20]:
#since we are more interested in the latter (p-values), we can judt take the second array
p_values=f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [21]:
#To be able to quickly evaluate them, we can round the result to 3 digits after the dot
p_values.round(3)

array([0.   , 0.676])